List<String> keywords = [
  "1:abstract:2",
  "2:as:2",
  "3:assert:",
  "4:async:1",
  "5:await:3",
  "6:break:",
  "7:case:",
  "8:catch:",
  "9:class:",
  "10:const:",
  "11:continue:",
  "12:convariant:2",
  "13:default:",
  "14:deferred:2",
  "15:do:",
  "16:dynamic:2",
  "17:else:",
  "18:enum:",
  "19:export:2",
  "20:extends:",
  "21:extension:2",
  "22:external:2",
  "23:factory:2",
  "24:false:",
  "25:final:",
  "26:finally:",
  "27:for:",
  "28:Function:2",
  "29:get:2",
  "30:hide:1",
  "31:if:",
  "32:implements:2",
  "33:import:2",
  "34:in:",
  "35:interface:2",
  "36:is:",
  "37:late:2",
  "38:library:2",
  "39:mixin:2",
  "40:new:",
  "41:null:",
  "42:on:1",
  "43:operator:2",
  "44:part:2",
  "45:required:2",
  "46:rethrow:",
  "47:return:",
  "48:set:2",
  "49:show:1",
  "50:static:2",
  "51:super:",
  "52:switch:",
  "53:sync:1",
  "54:this:",
  "55:throw:",
  "56:true:",
  "57:try:",
  "58:typedef:2",
  "59:var:",
  "60:void:",
  "61:while:",
  "62:with",
  "63:yield:3",
];

var s_one =
    "The Keyword with 1 are 'Contextual Keywords',which have meaning only in specific places. They're valid identifiers everywhere";
var s_two =
    "The Keyword with 2 are 'Build-in Identifiers, To simplify tha task of porting Javascript code to Dart, these keywords are valid Identifiers in most places, but they can't be used as class or type names, or as impoort prefixes'";
var s_three =
    "The keyword with 3 are limited reserved words related to 'asynchrony support'. await or yield, as an identifier in any function body marked with async, async*, or sync*";
var others =
    "All other words in the tables are reserved words, which can't be identifiers";
