enum DartLanguageTour {
  A_BASIC_DART_PROGRAM,
  IMPORTANT_CONCEPT,
  KEYWORDS,
  VARIABLES,
  DEFAULT_VALUE,
  LATE_VARIABLES,
  FINAL_AND_CONST,
  BUILT_IN_TYPES,
  NUMBERS,
  STRINGS,
  BOOLEANS,
  LISTS,
  SETS,
  MAPS,
  RUNES_AND_GRAPHEME_CLUSTER,
  SYMBOLS,
  FUNCTIONS,
  PARAMETERS,
  THE_MAIN_FUNCTION,
  FUNCTIONS_AS_FIRST_CLASS_OBJECTS,
  ANONYMOUS_FUNCTIONS,
  LEXICAL_SCOPE,
  LEXICAL_CLOSURES,
  TESTING_FUNCTIONS_FOR_EQUALITY,
  RETURN_VALUES,
  OPERATORS,
  ARITHMETIC_OPERATORS,
  EQUALITY_AND_RELATIONAL_OPERATORS,
  TYPE_TEST_OPERATORS,
  ASSIGNMENT_OPERATORS,
  LOGICAL_OPERATORS,
  BITWISE_AND_SHIFT_OPERATORS,
  CONDITIONAL_EXPRESSIONS,
  CASCADE_NOTATION,
  OTHER_OPERATORS,
  CONTROL_FLOW_STATEMENTS,
  IF_AND_ELSE,
  FOR_LOOPS,
  WHILE_AND_DO_WHILE,
  BREAK_AND_CONTINUE,
  SWITCH_AND_CASE,
  ASSET,
  EXCEPTIONS,
  THROW,
  CATCH,
  FINALLY,
  CLASSES,
  USING_CLASS_MEMBERS,
  USING_CONSTRUCTORS,
  GETTING_AN_OBJECTS_TYPE,
  INSTANCE_VARIABLES,
  CONSTRUCTORS,
  METHODS,
  ABSTRACT_CLASSES,
  IMPLICIT_INTERFACES,
  EXTENDING_A_CLASS,
  EXTENSION_METHODS,
  ENUMERATED_TYPES,
  ADDING_FEATURES_TO_A_CLASS_MIXINS,
  CLASS_VARIABLES_AND_METHODS,
  GENERICS,
  WHY_USE_GENERICS,
  USING_COLLECTION_LITERALS,
  USING_PARAMETERIZED_TYPES_WITH_CONSTRUCTORS,
  GENERIC_COLLECTIONS_AND_THE_TYPES_THEY_CONTAIN,
  RESTRICTING_THE_PARAMETERIZER_TYPE,
  USING_GENERIC_METHODS,
  LIBRARIES_AND_VISIBILITY,
  USING_LIBRARIES,
  IMPLEMENTING_LIBRARIES,
  ASYNCHRONY_SUPPORT,
  HANDLING_FUTURES,
  DECLARING_ASYNC_FUNCTIONS,
  HANDLING_STREAMS,
  GENERATORS,
  CALLABLE_CLASSES,
  ISOLATES,
  TYPEDEFS,
  METADATA,
  COMMENTS,
  SINGLE_LINE_COMMENTS,
  MULTI_LINE_COMMENTS,
  DOCUMENTATION_COMMENTS,
  SUMMARY
}

var variable = ["1:Dafault value", "2:Late variables", "3:Final and const"];
var built_in_types = [
  "1:Numbers",
  "2:Strings",
  "3:Booleans",
  "4:Lists",
  "5:Sets",
  "6:Maps",
  "7:Runes and grapheme cluster",
  "8:Symbols"
];
var functions = [
  "1:Parameters",
  "2:The main() functions",
  "3:Functions as first-class objects",
  "4:Anonymous functions",
  "5:Lexical scope",
  "6:Lexical closures",
  "7:Testing functions for equality",
  "8:Return values"
];

var operators = [
  "1:Arithmetic operators",
  "2:Equality and relational operators",
  "3:Type test operators",
  "4:Assignment operators",
  "5:Logical operators",
  "6:Bitwise and shift operators",
  "7:Conditional expressions",
  "8:Cascade notation",
  "9:Other operators",
];

var control_flow_statement = [
  "1:if and else",
  "2:For loops",
  "3:While and do-while",
  "4:Break and continue",
  "5:Switch and case",
  "6:Asset"
];

var exceptions = ["1:Throw", "2:Catch", "3:Finally"];

var classes = [
  "1:Using class members",
  "2:Using constructors",
  "3:Getting an object's type",
  "4:Instance variables",
  "5:Constructors",
  "6:Methods",
  "7:Abstract classes",
  "8:Implicit Interfaces",
  "9:Extending method",
  "10:Extension methods",
  "11:Enumerated methods",
  "12:Adding features to a class:mixins",
  "13:Class variables and method"
];

var generics = [
  "1:Why use generics?",
  "2:Using collection literals",
  "3:Using parameterized types with constructors",
  "4:Generic collections and the types they contain",
  "5:Restricting the parameterizer type",
  "6:Using generic methods",
];

var library_and_visibility = ["1:Using libraries", "2:Implementing libraries"];

var asynchrony_support = [
  "1:Handling Futures",
  "2:Declaring async functions",
  "3:Handling Streams"
];

var comments = [
  "1:Single-line comments",
  "2:Multi-line comments",
  "3:Documentation comments"
];

var language_tour = [
  "1:A basic Dart Program",
  "2:Important concept",
  "3:Keywords",
  "4:Variables",
  variable,
  "5:Built-in types",
  built_in_types,
  "6:Functions",
  functions,
  "7:Operators",
  operators,
  "8:Control flow statements",
  control_flow_statement,
  "9:Exceptions",
  exceptions,
  "10:Classes",
  classes,
  "11:Generics",
  generics,
  "12:Libraries and visibility",
  library_and_visibility,
  "13:Asynchrony support",
  asynchrony_support,
  "14:Generators",
  "15:Callable classes",
  "16:Isolates",
  "17:Typedefs",
  "18:Metadata",
  "19:Comments",
  comments,
  "20:Summary"
];

Map<String, List> lang_tour = {
  "A basic Dart Program": [],
  "Important concept": [],
  "Keywords": [],
  "Variables": variable,
  "Built-in types": built_in_types,
  "Functions": functions,
  "Operators": operators,
  "Control flow statements": control_flow_statement,
  "Exceptions": exceptions,
  "Classes": classes,
  "Generics": generics,
  "Libraries and visibility": library_and_visibility,
  "Asynchrony support": asynchrony_support,
  "Generators": [],
  "Callable classes": [],
  "Isolates": [],
  "Typedefs": [],
  "Metadata": [],
  "Comments": comments,
  "Summary": [],
};
